server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: bookService
          uri: http://localhost:8091/
          predicates:
            - Path=/api/v1/books/**
        - id: employeeService
          uri: http://localhost:8092/
          predicates:
            - Path=/api/v1/employees/**
        - id: borrowingService
          uri: http://localhost:8093/
          predicates:
            - Path=/api/v1/borrowing/**